/**
 * Automechanika trade-show offline shell. Cache-first, and precaches essentially everything
 * (pages, scripts, styles, fonts, videos, brand data, and the FULL images folder — vehicles/,
 * brands/, mock avatars, icons) on install, not just a "core shell" subset. Images requested by
 * a page's own <img> tags before this worker takes control of that page are never
 * opportunistically cached by the fetch handler below — a page's first load isn't "controlled"
 * yet — so anything left out of PRECACHE_URLS would silently stay missing offline regardless of
 * how much of the demo gets clicked through beforehand. Precaching everything up front (~40MB)
 * means one good load is genuinely enough; no rehearsal walkthrough required.
 *
 * CACHE_NAME includes the build timestamp, so every new deploy gets its own cache and the old
 * one is dropped on activate — no manual version bump needed.
 */
var CACHE_NAME = 'automechanika-1790243089938';

var PRECACHE_URLS = [
  '/diagnostics-pub/automechanika/',
  '/diagnostics-pub/automechanika/add-vci/',
  '/diagnostics-pub/automechanika/battery-soh-report/',
  '/diagnostics-pub/automechanika/dashboard/',
  '/diagnostics-pub/automechanika/diagnostics-dashboard/',
  '/diagnostics-pub/automechanika/diagnostics-dashboard-trucks/',
  '/diagnostics-pub/automechanika/ecu-detail/',
  '/diagnostics-pub/automechanika/get-started/',
  '/diagnostics-pub/automechanika/install/',
  '/diagnostics-pub/automechanika/login/',
  '/diagnostics-pub/automechanika/my-garage/',
  '/diagnostics-pub/automechanika/my-garage-trucks/',
  '/diagnostics-pub/automechanika/session-report/volvo-xc60-2014-session-4/',
  '/diagnostics-pub/automechanika/generate-report/volvo-xc60-2014-session-4/',
  '/diagnostics-pub/automechanika/session-report/volvo-xc60-2014-session-3/',
  '/diagnostics-pub/automechanika/generate-report/volvo-xc60-2014-session-3/',
  '/diagnostics-pub/automechanika/session-report/volvo-xc60-2014-session-2/',
  '/diagnostics-pub/automechanika/generate-report/volvo-xc60-2014-session-2/',
  '/diagnostics-pub/automechanika/session-report/volvo-xc60-2014-session-1/',
  '/diagnostics-pub/automechanika/generate-report/volvo-xc60-2014-session-1/',
  '/diagnostics-pub/automechanika/session-report/kia-niro-2020-session-1/',
  '/diagnostics-pub/automechanika/generate-report/kia-niro-2020-session-1/',
  '/diagnostics-pub/automechanika/session-report/ford-focus-2017-session-2/',
  '/diagnostics-pub/automechanika/generate-report/ford-focus-2017-session-2/',
  '/diagnostics-pub/automechanika/session-report/ford-focus-2017-session-1/',
  '/diagnostics-pub/automechanika/generate-report/ford-focus-2017-session-1/',
  '/diagnostics-pub/automechanika/session-report/renault-megane-e-tech-2024-session-3/',
  '/diagnostics-pub/automechanika/generate-report/renault-megane-e-tech-2024-session-3/',
  '/diagnostics-pub/automechanika/session-report/renault-megane-e-tech-2024-session-2/',
  '/diagnostics-pub/automechanika/generate-report/renault-megane-e-tech-2024-session-2/',
  '/diagnostics-pub/automechanika/session-report/renault-megane-e-tech-2024-session-1/',
  '/diagnostics-pub/automechanika/generate-report/renault-megane-e-tech-2024-session-1/',
  '/diagnostics-pub/automechanika/session-report/bmw-x5-2015-session-1/',
  '/diagnostics-pub/automechanika/generate-report/bmw-x5-2015-session-1/',
  '/diagnostics-pub/automechanika/session-report/bmw-330i-2018-session-2/',
  '/diagnostics-pub/automechanika/generate-report/bmw-330i-2018-session-2/',
  '/diagnostics-pub/automechanika/session-report/bmw-330i-2018-session-1/',
  '/diagnostics-pub/automechanika/generate-report/bmw-330i-2018-session-1/',
  '/diagnostics-pub/automechanika/session-report/audi-a6-2020-session-3/',
  '/diagnostics-pub/automechanika/generate-report/audi-a6-2020-session-3/',
  '/diagnostics-pub/automechanika/session-report/audi-a6-2020-session-2/',
  '/diagnostics-pub/automechanika/generate-report/audi-a6-2020-session-2/',
  '/diagnostics-pub/automechanika/session-report/audi-a6-2020-session-1/',
  '/diagnostics-pub/automechanika/generate-report/audi-a6-2020-session-1/',
  '/diagnostics-pub/automechanika/session-report/skoda-octavia-2017-session-1/',
  '/diagnostics-pub/automechanika/generate-report/skoda-octavia-2017-session-1/',
  '/diagnostics-pub/automechanika/session-report/toyota-corolla-2019-session-2/',
  '/diagnostics-pub/automechanika/generate-report/toyota-corolla-2019-session-2/',
  '/diagnostics-pub/automechanika/session-report/toyota-corolla-2019-session-1/',
  '/diagnostics-pub/automechanika/generate-report/toyota-corolla-2019-session-1/',
  '/diagnostics-pub/automechanika/session-report/peugeot-308-2021-session-3/',
  '/diagnostics-pub/automechanika/generate-report/peugeot-308-2021-session-3/',
  '/diagnostics-pub/automechanika/session-report/peugeot-308-2021-session-2/',
  '/diagnostics-pub/automechanika/generate-report/peugeot-308-2021-session-2/',
  '/diagnostics-pub/automechanika/session-report/peugeot-308-2021-session-1/',
  '/diagnostics-pub/automechanika/generate-report/peugeot-308-2021-session-1/',
  '/diagnostics-pub/automechanika/session-report/renault-megane-2020-session-1/',
  '/diagnostics-pub/automechanika/generate-report/renault-megane-2020-session-1/',
  '/diagnostics-pub/automechanika/session-report/seat-leon-2016-session-2/',
  '/diagnostics-pub/automechanika/generate-report/seat-leon-2016-session-2/',
  '/diagnostics-pub/automechanika/session-report/seat-leon-2016-session-1/',
  '/diagnostics-pub/automechanika/generate-report/seat-leon-2016-session-1/',
  '/diagnostics-pub/automechanika/session-report/opel-astra-2021-session-3/',
  '/diagnostics-pub/automechanika/generate-report/opel-astra-2021-session-3/',
  '/diagnostics-pub/automechanika/session-report/opel-astra-2021-session-2/',
  '/diagnostics-pub/automechanika/generate-report/opel-astra-2021-session-2/',
  '/diagnostics-pub/automechanika/session-report/opel-astra-2021-session-1/',
  '/diagnostics-pub/automechanika/generate-report/opel-astra-2021-session-1/',
  '/diagnostics-pub/automechanika/session-report/volvo-trucks-fh-2023-session-1/',
  '/diagnostics-pub/automechanika/generate-report/volvo-trucks-fh-2023-session-1/',
  '/diagnostics-pub/automechanika/session-report/man-tgx-2022-session-2/',
  '/diagnostics-pub/automechanika/generate-report/man-tgx-2022-session-2/',
  '/diagnostics-pub/automechanika/session-report/man-tgx-2022-session-1/',
  '/diagnostics-pub/automechanika/generate-report/man-tgx-2022-session-1/',
  '/diagnostics-pub/automechanika/session-report/volvo-trucks-fh16-2021-session-3/',
  '/diagnostics-pub/automechanika/generate-report/volvo-trucks-fh16-2021-session-3/',
  '/diagnostics-pub/automechanika/session-report/volvo-trucks-fh16-2021-session-2/',
  '/diagnostics-pub/automechanika/generate-report/volvo-trucks-fh16-2021-session-2/',
  '/diagnostics-pub/automechanika/session-report/volvo-trucks-fh16-2021-session-1/',
  '/diagnostics-pub/automechanika/generate-report/volvo-trucks-fh16-2021-session-1/',
  '/diagnostics-pub/automechanika/session-report/man-tgs-2020-session-1/',
  '/diagnostics-pub/automechanika/generate-report/man-tgs-2020-session-1/',
  '/diagnostics-pub/automechanika/session-report/volvo-trucks-fmx-2022-session-2/',
  '/diagnostics-pub/automechanika/generate-report/volvo-trucks-fmx-2022-session-2/',
  '/diagnostics-pub/automechanika/session-report/volvo-trucks-fmx-2022-session-1/',
  '/diagnostics-pub/automechanika/generate-report/volvo-trucks-fmx-2022-session-1/',
  '/diagnostics-pub/automechanika/session-report/volvo-xc60-2014-session-live/',
  '/diagnostics-pub/automechanika/generate-report/volvo-xc60-2014-session-live/',
  '/diagnostics-pub/automechanika/session-report/kia-niro-2020-session-live/',
  '/diagnostics-pub/automechanika/generate-report/kia-niro-2020-session-live/',
  '/diagnostics-pub/automechanika/session-report/ford-focus-2017-session-live/',
  '/diagnostics-pub/automechanika/generate-report/ford-focus-2017-session-live/',
  '/diagnostics-pub/automechanika/session-report/renault-megane-e-tech-2024-session-live/',
  '/diagnostics-pub/automechanika/generate-report/renault-megane-e-tech-2024-session-live/',
  '/diagnostics-pub/automechanika/session-report/bmw-x5-2015-session-live/',
  '/diagnostics-pub/automechanika/generate-report/bmw-x5-2015-session-live/',
  '/diagnostics-pub/automechanika/session-report/bmw-330i-2018-session-live/',
  '/diagnostics-pub/automechanika/generate-report/bmw-330i-2018-session-live/',
  '/diagnostics-pub/automechanika/session-report/audi-a6-2020-session-live/',
  '/diagnostics-pub/automechanika/generate-report/audi-a6-2020-session-live/',
  '/diagnostics-pub/automechanika/session-report/skoda-octavia-2017-session-live/',
  '/diagnostics-pub/automechanika/generate-report/skoda-octavia-2017-session-live/',
  '/diagnostics-pub/automechanika/session-report/toyota-corolla-2019-session-live/',
  '/diagnostics-pub/automechanika/generate-report/toyota-corolla-2019-session-live/',
  '/diagnostics-pub/automechanika/session-report/peugeot-308-2021-session-live/',
  '/diagnostics-pub/automechanika/generate-report/peugeot-308-2021-session-live/',
  '/diagnostics-pub/automechanika/session-report/renault-megane-2020-session-live/',
  '/diagnostics-pub/automechanika/generate-report/renault-megane-2020-session-live/',
  '/diagnostics-pub/automechanika/session-report/seat-leon-2016-session-live/',
  '/diagnostics-pub/automechanika/generate-report/seat-leon-2016-session-live/',
  '/diagnostics-pub/automechanika/session-report/opel-astra-2021-session-live/',
  '/diagnostics-pub/automechanika/generate-report/opel-astra-2021-session-live/',
  '/diagnostics-pub/automechanika/session-report/volvo-trucks-fh-2023-session-live/',
  '/diagnostics-pub/automechanika/generate-report/volvo-trucks-fh-2023-session-live/',
  '/diagnostics-pub/automechanika/session-report/man-tgx-2022-session-live/',
  '/diagnostics-pub/automechanika/generate-report/man-tgx-2022-session-live/',
  '/diagnostics-pub/automechanika/session-report/volvo-trucks-fh16-2021-session-live/',
  '/diagnostics-pub/automechanika/generate-report/volvo-trucks-fh16-2021-session-live/',
  '/diagnostics-pub/automechanika/session-report/man-tgs-2020-session-live/',
  '/diagnostics-pub/automechanika/generate-report/man-tgs-2020-session-live/',
  '/diagnostics-pub/automechanika/session-report/volvo-trucks-fmx-2022-session-live/',
  '/diagnostics-pub/automechanika/generate-report/volvo-trucks-fmx-2022-session-live/',
  '/diagnostics-pub/automechanika/settings/',
  '/diagnostics-pub/automechanika/tech-data/',
  '/diagnostics-pub/automechanika/theme-test/',
  '/diagnostics-pub/automechanika/vehicle-selection/',
  '/diagnostics-pub/automechanika/vehicle-selection-trucks/',
  '/diagnostics-pub/automechanika/welcome/',
  '/diagnostics-pub/automechanika/manifest.webmanifest',
  '/diagnostics-pub/assets/styles/main.css',
  '/diagnostics-pub/assets/videos/pouring-oil.mp4',
  '/diagnostics-pub/assets/videos/vci-pairing-tutorial.mp4',
  '/diagnostics-pub/assets/fonts/Fabrikat-Black.otf',
  '/diagnostics-pub/assets/fonts/Fabrikat-Bold.otf',
  '/diagnostics-pub/assets/fonts/Fabrikat.otf',
  '/diagnostics-pub/assets/fonts/WorkSans-Bold.woff2',
  '/diagnostics-pub/assets/fonts/WorkSans-Medium.woff2',
  '/diagnostics-pub/assets/fonts/WorkSans-Regular.woff2',
  '/diagnostics-pub/assets/fonts/WorkSans-SemiBold.woff2',
  '/diagnostics-pub/assets/scripts/vendor/confetti.browser.min.js',
  '/diagnostics-pub/assets/scripts/add-vci.js',
  '/diagnostics-pub/assets/scripts/automechanika-nav.js',
  '/diagnostics-pub/assets/scripts/battery-soh-modal.js',
  '/diagnostics-pub/assets/scripts/battery-soh-report.js',
  '/diagnostics-pub/assets/scripts/bms-dtc-library.js',
  '/diagnostics-pub/assets/scripts/clearable-input.js',
  '/diagnostics-pub/assets/scripts/connectivity-check.js',
  '/diagnostics-pub/assets/scripts/diagnostics-dashboard.js',
  '/diagnostics-pub/assets/scripts/data-lists-library.js',
  '/diagnostics-pub/assets/scripts/data-lists-modal.js',
  '/diagnostics-pub/assets/scripts/dtc-detail-modal.js',
  '/diagnostics-pub/assets/scripts/dtc-library.js',
  '/diagnostics-pub/assets/scripts/ecu-detail.js',
  '/diagnostics-pub/assets/scripts/functions-library.js',
  '/diagnostics-pub/assets/scripts/get-started.js',
  '/diagnostics-pub/assets/scripts/garage.js',
  '/diagnostics-pub/assets/scripts/garage-live-session.js',
  '/diagnostics-pub/assets/scripts/hero-vin-vrm.js',
  '/diagnostics-pub/assets/scripts/index-onboarding.js',
  '/diagnostics-pub/assets/scripts/install.js',
  '/diagnostics-pub/assets/scripts/live-session.js',
  '/diagnostics-pub/assets/scripts/live-report.js',
  '/diagnostics-pub/assets/scripts/login.js',
  '/diagnostics-pub/assets/scripts/notifications.js',
  '/diagnostics-pub/assets/scripts/onboarding-drawer.js',
  '/diagnostics-pub/assets/scripts/onboarding-waypoint-tour.js',
  '/diagnostics-pub/assets/scripts/prototype-gate.js',
  '/diagnostics-pub/assets/scripts/trial-expired-gate.js',
  '/diagnostics-pub/assets/scripts/report-composer.js',
  '/diagnostics-pub/assets/scripts/report-shared.js',
  '/diagnostics-pub/assets/scripts/scan-vin-modal.js',
  '/diagnostics-pub/assets/scripts/vci-pair-detect-modal.js',
  '/diagnostics-pub/assets/scripts/vehicle-selection.js',
  '/diagnostics-pub/assets/scripts/diagnostic-functions.js',
  '/diagnostics-pub/assets/scripts/welcome.js',
  '/diagnostics-pub/assets/data/brands_models/abarth_models.json',
  '/diagnostics-pub/assets/data/brands_models/alfa_romeo_models.json',
  '/diagnostics-pub/assets/data/brands_models/audi_models.json',
  '/diagnostics-pub/assets/data/brands_models/bentley_models.json',
  '/diagnostics-pub/assets/data/brands_models/bmw_models.json',
  '/diagnostics-pub/assets/data/brands_models/byd_models.json',
  '/diagnostics-pub/assets/data/brands_models/cadillac_models.json',
  '/diagnostics-pub/assets/data/brands_models/chevrolet_models.json',
  '/diagnostics-pub/assets/data/brands_models/chrysler_models.json',
  '/diagnostics-pub/assets/data/brands_models/citroen_models.json',
  '/diagnostics-pub/assets/data/brands_models/cupra_models.json',
  '/diagnostics-pub/assets/data/brands_models/dacia_models.json',
  '/diagnostics-pub/assets/data/brands_models/daewoo_models.json',
  '/diagnostics-pub/assets/data/brands_models/daihatsu_models.json',
  '/diagnostics-pub/assets/data/brands_models/dodge_models.json',
  '/diagnostics-pub/assets/data/brands_models/ds_automobiles_models.json',
  '/diagnostics-pub/assets/data/brands_models/ferrari_models.json',
  '/diagnostics-pub/assets/data/brands_models/fiat_models.json',
  '/diagnostics-pub/assets/data/brands_models/ford_models.json',
  '/diagnostics-pub/assets/data/brands_models/foton_models.json',
  '/diagnostics-pub/assets/data/brands_models/gaz_models.json',
  '/diagnostics-pub/assets/data/brands_models/gwm_models.json',
  '/diagnostics-pub/assets/data/brands_models/honda_models.json',
  '/diagnostics-pub/assets/data/brands_models/hyundai_models.json',
  '/diagnostics-pub/assets/data/brands_models/infiniti_models.json',
  '/diagnostics-pub/assets/data/brands_models/isuzu_models.json',
  '/diagnostics-pub/assets/data/brands_models/iveco_models.json',
  '/diagnostics-pub/assets/data/brands_models/jaguar_models.json',
  '/diagnostics-pub/assets/data/brands_models/jeep_models.json',
  '/diagnostics-pub/assets/data/brands_models/jinbei_models.json',
  '/diagnostics-pub/assets/data/brands_models/jmc_models.json',
  '/diagnostics-pub/assets/data/brands_models/kia_models.json',
  '/diagnostics-pub/assets/data/brands_models/lada_models.json',
  '/diagnostics-pub/assets/data/brands_models/lamborghini_models.json',
  '/diagnostics-pub/assets/data/brands_models/lancia_models.json',
  '/diagnostics-pub/assets/data/brands_models/land_rover_models.json',
  '/diagnostics-pub/assets/data/brands_models/lexus_models.json',
  '/diagnostics-pub/assets/data/brands_models/lotus_models.json',
  '/diagnostics-pub/assets/data/brands_models/maserati_models.json',
  '/diagnostics-pub/assets/data/brands_models/mazda_models.json',
  '/diagnostics-pub/assets/data/brands_models/mercedes-benz_models.json',
  '/diagnostics-pub/assets/data/brands_models/mg_models.json',
  '/diagnostics-pub/assets/data/brands_models/mini_models.json',
  '/diagnostics-pub/assets/data/brands_models/mitsubishi_models.json',
  '/diagnostics-pub/assets/data/brands_models/nissan_models.json',
  '/diagnostics-pub/assets/data/brands_models/opel_models.json',
  '/diagnostics-pub/assets/data/brands_models/peugeot_models.json',
  '/diagnostics-pub/assets/data/brands_models/porsche_models.json',
  '/diagnostics-pub/assets/data/brands_models/renault_models.json',
  '/diagnostics-pub/assets/data/brands_models/seat_models.json',
  '/diagnostics-pub/assets/data/brands_models/skoda_models.json',
  '/diagnostics-pub/assets/data/brands_models/smart_models.json',
  '/diagnostics-pub/assets/data/brands_models/suzuki_models.json',
  '/diagnostics-pub/assets/data/brands_models/toyota_models.json',
  '/diagnostics-pub/assets/data/brands_models/volkswagen_models.json',
  '/diagnostics-pub/assets/data/brands_models/volvo_models.json',
  '/diagnostics-pub/assets/data/brands_models_trucks/volvo_trucks_models.json',
  '/diagnostics-pub/assets/data/brands_models_trucks/man_trucks_models.json',
  '/diagnostics-pub/assets/images/1730130528-mechanic-2-icon-highres.avif',
  '/diagnostics-pub/assets/images/1749557346-emdoor-em-120a-tablet.avif',
  '/diagnostics-pub/assets/images/autocom-symbol.svg',
  '/diagnostics-pub/assets/images/beehive.svg',
  '/diagnostics-pub/assets/images/brands/abarth.png',
  '/diagnostics-pub/assets/images/brands/alfa-romeo.png',
  '/diagnostics-pub/assets/images/brands/audi.png',
  '/diagnostics-pub/assets/images/brands/bentley.png',
  '/diagnostics-pub/assets/images/brands/bmw.png',
  '/diagnostics-pub/assets/images/brands/byd.png',
  '/diagnostics-pub/assets/images/brands/cadillac.png',
  '/diagnostics-pub/assets/images/brands/chevrolet.png',
  '/diagnostics-pub/assets/images/brands/chrysler.png',
  '/diagnostics-pub/assets/images/brands/citroen.png',
  '/diagnostics-pub/assets/images/brands/cupra.png',
  '/diagnostics-pub/assets/images/brands/dacia.png',
  '/diagnostics-pub/assets/images/brands/daewoo.png',
  '/diagnostics-pub/assets/images/brands/daihatsu.png',
  '/diagnostics-pub/assets/images/brands/dodge.png',
  '/diagnostics-pub/assets/images/brands/ds-automobiles.png',
  '/diagnostics-pub/assets/images/brands/ferrari.png',
  '/diagnostics-pub/assets/images/brands/fiat.png',
  '/diagnostics-pub/assets/images/brands/ford.png',
  '/diagnostics-pub/assets/images/brands/foton.png',
  '/diagnostics-pub/assets/images/brands/gaz.png',
  '/diagnostics-pub/assets/images/brands/gwm.png',
  '/diagnostics-pub/assets/images/brands/honda.png',
  '/diagnostics-pub/assets/images/brands/hyundai.png',
  '/diagnostics-pub/assets/images/brands/infiniti.png',
  '/diagnostics-pub/assets/images/brands/isuzu.png',
  '/diagnostics-pub/assets/images/brands/iveco.png',
  '/diagnostics-pub/assets/images/brands/jaguar.png',
  '/diagnostics-pub/assets/images/brands/jeep.png',
  '/diagnostics-pub/assets/images/brands/jinbei.png',
  '/diagnostics-pub/assets/images/brands/jmc.png',
  '/diagnostics-pub/assets/images/brands/kia.png',
  '/diagnostics-pub/assets/images/brands/lada.png',
  '/diagnostics-pub/assets/images/brands/ladog.png',
  '/diagnostics-pub/assets/images/brands/lamborghini.png',
  '/diagnostics-pub/assets/images/brands/lancia.png',
  '/diagnostics-pub/assets/images/brands/land-rover.png',
  '/diagnostics-pub/assets/images/brands/lexus.png',
  '/diagnostics-pub/assets/images/brands/lotus.png',
  '/diagnostics-pub/assets/images/brands/maserati.png',
  '/diagnostics-pub/assets/images/brands/mazda.png',
  '/diagnostics-pub/assets/images/brands/mercedes-benz.png',
  '/diagnostics-pub/assets/images/brands/mg.png',
  '/diagnostics-pub/assets/images/brands/mini.png',
  '/diagnostics-pub/assets/images/brands/mitsubishi.png',
  '/diagnostics-pub/assets/images/brands/nissan.png',
  '/diagnostics-pub/assets/images/brands/opel.png',
  '/diagnostics-pub/assets/images/brands/peugeot.png',
  '/diagnostics-pub/assets/images/brands/porsche.png',
  '/diagnostics-pub/assets/images/brands/renault.png',
  '/diagnostics-pub/assets/images/brands/seat.png',
  '/diagnostics-pub/assets/images/brands/skoda.png',
  '/diagnostics-pub/assets/images/brands/smart.png',
  '/diagnostics-pub/assets/images/brands/suzuki.png',
  '/diagnostics-pub/assets/images/brands/toyota.png',
  '/diagnostics-pub/assets/images/brands/volkswagen.png',
  '/diagnostics-pub/assets/images/brands/volvo.png',
  '/diagnostics-pub/assets/images/brands-trucks/man-trucks.png',
  '/diagnostics-pub/assets/images/brands-trucks/volvo-trucks.png',
  '/diagnostics-pub/assets/images/icons/icon-192.png',
  '/diagnostics-pub/assets/images/icons/icon-512.png',
  '/diagnostics-pub/assets/images/icons/icon-maskable-512.png',
  '/diagnostics-pub/assets/images/obd-socket/truck-cab.png',
  '/diagnostics-pub/assets/images/pragmatic-follower.png',
  '/diagnostics-pub/assets/images/risk-owner.png',
  '/diagnostics-pub/assets/images/sms-trusted.svg',
  '/diagnostics-pub/assets/images/sms-verify.svg',
  '/diagnostics-pub/assets/images/tinkerer.png',
  '/diagnostics-pub/assets/images/vci-icon-1.png',
  '/diagnostics-pub/assets/images/vci-icon-front.png',
  '/diagnostics-pub/assets/images/vci-old-1.png',
  '/diagnostics-pub/assets/images/vci-pairing-tutorial-poster.png',
  '/diagnostics-pub/assets/images/vehicles/Audi_A3_sedan_2024.png',
  '/diagnostics-pub/assets/images/vehicles/Audi_A4_2017.png',
  '/diagnostics-pub/assets/images/vehicles/Audi_A6_sedan_S-Line_2023.png',
  '/diagnostics-pub/assets/images/vehicles/Citroen_C3_2017.png',
  '/diagnostics-pub/assets/images/vehicles/Citroen_C3_L_sedan_2020.png',
  '/diagnostics-pub/assets/images/vehicles/Citroen_C4_Cactus_2015.png',
  '/diagnostics-pub/assets/images/vehicles/Citroen_C4_Picasso_2016.png',
  '/diagnostics-pub/assets/images/vehicles/Dacia_Duster_Extreme_2024.png',
  '/diagnostics-pub/assets/images/vehicles/Dacia_Sandero_2021.png',
  '/diagnostics-pub/assets/images/vehicles/Fiat_Argo_2017.png',
  '/diagnostics-pub/assets/images/vehicles/Fiat_Panda_Cross_2014.png',
  '/diagnostics-pub/assets/images/vehicles/Fiat_Pulse_Impetus_2021.png',
  '/diagnostics-pub/assets/images/vehicles/Fiat_Tipo_2020.png',
  '/diagnostics-pub/assets/images/vehicles/Ford_Focus_ST_Line_2018.png',
  '/diagnostics-pub/assets/images/vehicles/Ford_Focus_Titanium_2018.png',
  '/diagnostics-pub/assets/images/vehicles/Honda_Civic_coupe_2016.png',
  '/diagnostics-pub/assets/images/vehicles/Hyundai_i30_GD_2015.png',
  '/diagnostics-pub/assets/images/vehicles/Hyundai_i30_PD_2024.png',
  '/diagnostics-pub/assets/images/vehicles/Kia_Ceed_hatchback_2018.png',
  '/diagnostics-pub/assets/images/vehicles/Mazda_3_sedan_2019.png',
  '/diagnostics-pub/assets/images/vehicles/Nissan_Qashqai_2017.png',
  '/diagnostics-pub/assets/images/vehicles/Opel_Astra_K_2016.png',
  '/diagnostics-pub/assets/images/vehicles/Opel_Astra_L_Hybrid_2021.png',
  '/diagnostics-pub/assets/images/vehicles/Peugeot_308_P5_HYBRID_2021.png',
  '/diagnostics-pub/assets/images/vehicles/Peugeot_308_T9_2017.png',
  '/diagnostics-pub/assets/images/vehicles/Peugeot_308_T9_sedan_2017.png',
  '/diagnostics-pub/assets/images/vehicles/Renault_Megane_hatchback_2014.png',
  '/diagnostics-pub/assets/images/vehicles/Renault_Megane_sedan_2020.png',
  '/diagnostics-pub/assets/images/vehicles/Seat_Leon_5F_FR_2016.png',
  '/diagnostics-pub/assets/images/vehicles/Seat_Leon_FR_eHybrid_2020.png',
  '/diagnostics-pub/assets/images/vehicles/Skoda_Octavia_1Z_liftback_2005.png',
  '/diagnostics-pub/assets/images/vehicles/Skoda_Octavia_5E_liftback_2017.png',
  '/diagnostics-pub/assets/images/vehicles/Skoda_Octavia_liftback_2013.png',
  '/diagnostics-pub/assets/images/vehicles/Toyota_Corolla_E210_hybrid_2018.png',
  '/diagnostics-pub/assets/images/vehicles/Toyota_Corolla_E210_sedan_Hybrid_2019.png',
  '/diagnostics-pub/assets/images/vehicles/Volkswagen_Golf_2024.png',
  '/diagnostics-pub/assets/images/vehicles/Volkswagen_Golf__2018.png',
  '/diagnostics-pub/assets/images/vehicles/Volkswagen_T-Cross_2022.png',
  '/diagnostics-pub/assets/images/vehicles/Volkswagen_Touareg_2023.png',
  '/diagnostics-pub/assets/images/vehicles/Volvo_V60_D4_2015.png',
  '/diagnostics-pub/assets/images/vehicles/Volvo_XC60_2014.png',
  '/diagnostics-pub/assets/images/vehicles/Volvo_XC60_T6_2017.png',
  '/diagnostics-pub/assets/images/vehicles-trucks/man-truck-demo.png',
  '/diagnostics-pub/assets/images/vehicles-trucks/volvo-fh-xl-chassis-truck-4-axle-2025.png'
];

self.addEventListener('install', function (event) {
  event.waitUntil(
    caches.open(CACHE_NAME).then(function (cache) {
      return cache.addAll(PRECACHE_URLS);
    }).then(function () {
      return self.skipWaiting();
    })
  );
});

self.addEventListener('activate', function (event) {
  event.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(
        keys.filter(function (key) { return key !== CACHE_NAME; })
          .map(function (key) { return caches.delete(key); })
      );
    }).then(function () {
      return self.clients.claim();
    })
  );
});

self.addEventListener('fetch', function (event) {
  if (event.request.method !== 'GET') return;
  var url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;

  // Page navigations carry demo-state query params (e.g. diagnostics-dashboard?vin=...&brand=...)
  // that vary per session — the underlying HTML shell is identical and precached without a query
  // string, so match those ignoring search, or every such navigation would cache-miss and (while
  // offline) silently fall back to the dashboard instead of showing the actual page.
  var isNavigate = event.request.mode === 'navigate';

  event.respondWith(
    (isNavigate ? caches.match(event.request, { ignoreSearch: true }) : caches.match(event.request)).then(function (cached) {
      if (cached) return cached;
      return fetch(event.request).then(function (response) {
        if (response && response.ok) {
          var copy = response.clone();
          caches.open(CACHE_NAME).then(function (cache) { cache.put(event.request, copy); });
        }
        return response;
      }).catch(function () {
        if (isNavigate) return caches.match('/diagnostics-pub/automechanika/');
      });
    })
  );
});
